#include "main.h"

/**
 *_free_str - free tok & line
 *@tok: array of tokens
 *@line: string of characetr generated by get line
 *Return: always 1
 */

int _free_str(char **tok, char *line)
{
free(tok);
free(line);

return (1);
}

/**
 *concat_path - fin the full path
 *@tok: array of tokens. Return of token
 *@path:array of directorys. Return of getenv
 *Retunr: a pointer to the new tok
 */
/**
char **concat_path(char **tok, char **path)
{
list_t token_path;

token_path = malloc(1024);

token(*path, ":");
return (tok);
}
*/
